title: 5key guidebook
description: a collective on information for the game series beatmania, both on arcade and console. (and maybe EZ2DJ too?)
theme: just-the-docs

url: https://infinitephantasm.github.io/5key-guidebook
